// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto3/route_guide.proto

package com.jachs.protocolbuffers.proto3.routeguide;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1;</code>
   * @return The latitude.
   */
  int getLatitude();

  /**
   * <code>int32 longitude = 2;</code>
   * @return The longitude.
   */
  int getLongitude();
}
