// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto3/hello_streaming.proto

package com.jachs.protocolbuffers.proto3.manualflowcontrol;

public final class HelloStreamingProto {
  private HelloStreamingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_manualflowcontrol_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_manualflowcontrol_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_manualflowcontrol_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_manualflowcontrol_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/main/resources/proto3/hello_stream" +
      "ing.proto\022\021manualflowcontrol\"\034\n\014HelloReq" +
      "uest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007mess" +
      "age\030\001 \001(\t2m\n\020StreamingGreeter\022Y\n\021SayHell" +
      "oStreaming\022\037.manualflowcontrol.HelloRequ" +
      "est\032\035.manualflowcontrol.HelloReply\"\000(\0010\001" +
      "BR\n2com.jachs.protocolbuffers.proto3.man" +
      "ualflowcontrolB\023HelloStreamingProtoP\001\242\002\004" +
      "HLWSb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_manualflowcontrol_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_manualflowcontrol_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_manualflowcontrol_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_manualflowcontrol_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_manualflowcontrol_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_manualflowcontrol_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
