// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto3/hello_streaming.proto

package com.jachs.protocolbuffers.proto3.manualflowcontrol;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:manualflowcontrol.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
